apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    proj: axe
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      proj: axe
  template:
    metadata:
      name: axe
      labels:
        proj: axe
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.deployment.imageVersion }}
        command: ["nginx", "-g", "daemon off"]